---
apiVersion: v1
kind: Service
metadata:
  name: app-annrod-test-flask-service
  labels:
    username: ann_rod
    env: test
spec:
  type: ClusterIP
  selector:
    app: annrod-test-flask
    username: ann_rod
    env: test
  ports:
  - name: helloflask
    port: 5000
    targetPort: 5000
