---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-annrod-test-redis-pvc-data
  labels:
    username: ann_rod
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
